@php
    $record = $visit->medicalRecord;
    $isFinal = $record->status === \App\MedicalRecordStatus::Final;
    $vital = $record->vitalSign;
    $diagnosisRows = old('diagnoses', $record->diagnoses->map(fn ($item) => [
        'code' => $item->code ?? '', 'name' => $item->name, 'notes' => $item->notes ?? '', 'is_primary' => $item->is_primary ? '1' : '0',
    ])->all());
    $treatmentRows = old('treatments', $record->treatments->map(fn ($item) => [
        'name' => $item->name, 'description' => $item->description ?? '',
    ])->all());
    $prescriptionRows = old('prescription_items', $record->prescription?->items->map(fn ($item) => [
        'medicine_name' => $item->medicine_name, 'dosage' => $item->dosage, 'frequency' => $item->frequency,
        'quantity' => $item->quantity, 'unit' => $item->unit ?? '', 'instructions' => $item->instructions ?? '',
    ])->all() ?? []);
    $diagnosisRows = $diagnosisRows ?: [['code' => '', 'name' => '', 'notes' => '', 'is_primary' => '1']];
    $treatmentRows = $treatmentRows ?: [['name' => '', 'description' => '']];
    $prescriptionRows = $prescriptionRows ?: [['medicine_name' => '', 'dosage' => '', 'frequency' => '', 'quantity' => '', 'unit' => '', 'instructions' => '']];
@endphp
<x-app-layout>
    <x-slot name="header"><div class="flex w-full items-center justify-between gap-4"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">{{ $visit->appointment->booking_code }} · {{ $visit->queue->display_number }}</p><h1 class="mt-1 text-xl font-extrabold text-clinic-950">Pemeriksaan pasien</h1></div><span class="{{ $isFinal ? 'clinic-status-active' : 'rounded-full bg-amber-100 px-3 py-1.5 text-xs font-bold text-amber-700' }}">{{ $isFinal ? 'Final' : 'Draft' }}</span></div></x-slot>

    @if($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700"><p class="font-bold">Periksa kembali rekam medis:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

    <div class="grid gap-6 xl:grid-cols-[1fr_320px]">
        <form method="POST" action="{{ $isFinal ? route('doctor.visits.correct', $visit) : route('doctor.visits.save', $visit) }}" class="space-y-6" x-data="{ diagnoses: @js($diagnosisRows), treatments: @js($treatmentRows), medicines: @js($prescriptionRows), submitting: false }" @submit="submitting = true">
            @csrf @method('PUT')
            <section class="clinic-card p-6 sm:p-8"><div class="flex flex-wrap items-start justify-between gap-5"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Pasien</p><h2 class="mt-2 text-2xl font-extrabold text-clinic-950">{{ $visit->patient->name }}</h2><p class="mt-1 text-sm text-slate-500">{{ $visit->patient->medical_record_number }} · {{ $visit->patient->birth_date->age }} tahun · {{ $visit->patient->gender === 'MALE' ? 'Laki-laki' : 'Perempuan' }}</p></div><div class="text-left sm:text-right"><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Layanan</p><p class="mt-2 font-bold text-slate-900">{{ $visit->service_name }}</p><p class="mt-1 text-sm text-clinic-600">Rp {{ number_format((float) $visit->service_price, 0, ',', '.') }}</p></div></div></section>

            @if($isFinal)<section class="rounded-2xl border border-amber-200 bg-amber-50 p-5"><p class="font-bold text-amber-900">Mode koreksi rekam medis final</p><p class="mt-1 text-sm leading-6 text-amber-700">Perubahan akan menyimpan snapshot sebelum dan sesudah koreksi. Isi alasan yang spesifik.</p><label class="clinic-label mt-4" for="correction_reason">Alasan koreksi</label><textarea class="clinic-input" id="correction_reason" name="correction_reason" rows="2" required>{{ old('correction_reason') }}</textarea></section>@endif

            <section class="clinic-card p-6 sm:p-8"><h2 class="text-lg font-extrabold text-clinic-950">Keluhan & SOAP</h2><div class="mt-6 grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><label class="clinic-label" for="chief_complaint">Keluhan utama</label><textarea class="clinic-input" id="chief_complaint" name="chief_complaint" rows="3">{{ old('chief_complaint', $record->chief_complaint) }}</textarea></div><div><label class="clinic-label" for="subjective">Subjective</label><textarea class="clinic-input" id="subjective" name="subjective" rows="5">{{ old('subjective', $record->subjective) }}</textarea></div><div><label class="clinic-label" for="objective">Objective</label><textarea class="clinic-input" id="objective" name="objective" rows="5">{{ old('objective', $record->objective) }}</textarea></div><div><label class="clinic-label" for="assessment">Assessment</label><textarea class="clinic-input" id="assessment" name="assessment" rows="5">{{ old('assessment', $record->assessment) }}</textarea></div><div><label class="clinic-label" for="plan">Plan</label><textarea class="clinic-input" id="plan" name="plan" rows="5">{{ old('plan', $record->plan) }}</textarea></div><div class="md:col-span-2"><label class="clinic-label" for="physical_examination">Pemeriksaan fisik</label><textarea class="clinic-input" id="physical_examination" name="physical_examination" rows="3">{{ old('physical_examination', $record->physical_examination) }}</textarea></div></div></section>

            <section class="clinic-card p-6 sm:p-8"><h2 class="text-lg font-extrabold text-clinic-950">Tanda vital</h2><div class="mt-6 grid grid-cols-2 gap-4 md:grid-cols-4">@foreach([['weight_kg','Berat','kg','0.1'],['height_cm','Tinggi','cm','0.1'],['systolic','Sistolik','mmHg','1'],['diastolic','Diastolik','mmHg','1'],['pulse','Nadi','/menit','1'],['respiratory_rate','Pernapasan','/menit','1'],['temperature_c','Suhu','°C','0.1'],['oxygen_saturation','SpO₂','%','1']] as [$name,$label,$unit,$step])<div><label class="clinic-label" for="vital_{{ $name }}">{{ $label }}</label><div class="relative"><input class="clinic-input pr-16" id="vital_{{ $name }}" name="vital_signs[{{ $name }}]" type="number" step="{{ $step }}" value="{{ old('vital_signs.'.$name, $vital?->{$name}) }}"><span class="absolute right-3 top-3 text-xs text-slate-400">{{ $unit }}</span></div></div>@endforeach</div></section>

            <section class="clinic-card p-6 sm:p-8"><div class="flex items-center justify-between"><div><h2 class="text-lg font-extrabold text-clinic-950">Diagnosis</h2><p class="mt-1 text-sm text-slate-500">Minimal satu diagnosis saat finalisasi.</p></div><button type="button" @click="diagnoses.push({code:'',name:'',notes:'',is_primary:'0'})" class="clinic-button-secondary px-4 py-2">+ Diagnosis</button></div><div class="mt-6 space-y-4"><template x-for="(item, index) in diagnoses" :key="index"><div class="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[120px_1fr_140px_auto]"><input class="clinic-input" :name="`diagnoses[${index}][code]`" x-model="item.code" placeholder="Kode"><input class="clinic-input" :name="`diagnoses[${index}][name]`" x-model="item.name" placeholder="Nama diagnosis"><select class="clinic-input" :name="`diagnoses[${index}][is_primary]`" x-model="item.is_primary"><option value="1">Utama</option><option value="0">Sekunder</option></select><button type="button" @click="diagnoses.splice(index,1)" class="px-3 font-bold text-red-500">Hapus</button><textarea class="clinic-input md:col-span-4" :name="`diagnoses[${index}][notes]`" x-model="item.notes" rows="2" placeholder="Catatan diagnosis"></textarea></div></template></div></section>

            <section class="clinic-card p-6 sm:p-8"><div class="flex items-center justify-between"><h2 class="text-lg font-extrabold text-clinic-950">Tindakan</h2><button type="button" @click="treatments.push({name:'',description:''})" class="clinic-button-secondary px-4 py-2">+ Tindakan</button></div><div class="mt-6 space-y-4"><template x-for="(item, index) in treatments" :key="index"><div class="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-[1fr_auto]"><input class="clinic-input" :name="`treatments[${index}][name]`" x-model="item.name" placeholder="Nama tindakan"><button type="button" @click="treatments.splice(index,1)" class="px-3 font-bold text-red-500">Hapus</button><textarea class="clinic-input md:col-span-2" :name="`treatments[${index}][description]`" x-model="item.description" rows="2" placeholder="Keterangan tindakan"></textarea></div></template></div></section>

            <section class="clinic-card p-6 sm:p-8"><div class="flex items-center justify-between"><h2 class="text-lg font-extrabold text-clinic-950">Resep</h2><button type="button" @click="medicines.push({medicine_name:'',dosage:'',frequency:'',quantity:'',unit:'',instructions:''})" class="clinic-button-secondary px-4 py-2">+ Obat</button></div><div class="mt-6 space-y-4"><template x-for="(item, index) in medicines" :key="index"><div class="grid gap-3 rounded-2xl bg-slate-50 p-4 md:grid-cols-3"><input class="clinic-input" :name="`prescription_items[${index}][medicine_name]`" x-model="item.medicine_name" placeholder="Nama obat"><input class="clinic-input" :name="`prescription_items[${index}][dosage]`" x-model="item.dosage" placeholder="Dosis"><input class="clinic-input" :name="`prescription_items[${index}][frequency]`" x-model="item.frequency" placeholder="Frekuensi"><input class="clinic-input" :name="`prescription_items[${index}][quantity]`" x-model="item.quantity" type="number" min="1" placeholder="Jumlah"><input class="clinic-input" :name="`prescription_items[${index}][unit]`" x-model="item.unit" placeholder="Satuan"><button type="button" @click="medicines.splice(index,1)" class="px-3 text-left font-bold text-red-500 md:text-center">Hapus</button><textarea class="clinic-input md:col-span-3" :name="`prescription_items[${index}][instructions]`" x-model="item.instructions" rows="2" placeholder="Instruksi penggunaan"></textarea></div></template><div><label class="clinic-label" for="prescription_notes">Catatan resep</label><textarea class="clinic-input" id="prescription_notes" name="prescription_notes" rows="2">{{ old('prescription_notes', $record->prescription?->notes) }}</textarea></div></div></section>

            <section class="clinic-card p-6 sm:p-8"><label class="clinic-label" for="doctor_notes">Catatan dokter</label><textarea class="clinic-input" id="doctor_notes" name="doctor_notes" rows="4">{{ old('doctor_notes', $record->doctor_notes) }}</textarea></section>

            <div class="flex flex-col justify-end gap-3 sm:flex-row">@if($isFinal)<button class="clinic-button-primary disabled:opacity-60" :disabled="submitting">Simpan koreksi</button>@else<button class="clinic-button-secondary disabled:opacity-60" :disabled="submitting" formnovalidate>Simpan draft</button><button class="clinic-button-primary disabled:opacity-60" :disabled="submitting" formaction="{{ route('doctor.visits.complete', $visit) }}" onclick="return confirm('Finalisasi kunjungan? Rekam medis hanya dapat diubah melalui koreksi beralasan.')">Selesaikan kunjungan</button>@endif</div>
        </form>

        <aside class="space-y-6"><section class="clinic-card p-6"><h2 class="font-extrabold text-clinic-950">Kunjungan</h2><dl class="mt-5 space-y-4 text-sm"><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Mulai</dt><dd class="mt-1 font-semibold">{{ $visit->started_at->format('d M Y, H:i') }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Dokter</dt><dd class="mt-1 font-semibold">{{ $visit->doctor->user->name }}</dd></div><div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Nilai layanan</dt><dd class="mt-1 font-semibold">Rp {{ number_format((float) $visit->total_amount, 0, ',', '.') }}</dd></div>@if($visit->completed_at)<div><dt class="text-xs font-bold uppercase tracking-wider text-slate-400">Selesai</dt><dd class="mt-1 font-semibold">{{ $visit->completed_at->format('d M Y, H:i') }}</dd></div>@endif</dl></section>
            <section class="clinic-card overflow-hidden"><div class="border-b border-slate-100 p-5"><h2 class="font-extrabold text-clinic-950">Riwayat dengan dokter ini</h2></div><div class="divide-y divide-slate-100">@forelse($history as $item)<a href="{{ route('doctor.visits.show', $item) }}" class="block p-5 hover:bg-slate-50" wire:navigate><p class="text-sm font-bold text-slate-900">{{ $item->started_at->format('d M Y') }}</p><p class="mt-1 text-xs text-slate-500">{{ $item->service_name }} · {{ $item->status->value }}</p><p class="mt-2 text-xs font-semibold text-clinic-700">{{ $item->medicalRecord?->diagnoses->pluck('name')->join(', ') ?: 'Belum ada diagnosis' }}</p></a>@empty<div class="p-6 text-sm text-slate-500">Belum ada kunjungan sebelumnya.</div>@endforelse</div></section>
            @if($record->revisions->isNotEmpty())<section class="clinic-card p-6"><h2 class="font-extrabold text-clinic-950">Riwayat koreksi</h2><div class="mt-4 space-y-4">@foreach($record->revisions as $revision)<div class="border-l-2 border-amber-300 pl-3"><p class="text-sm font-semibold text-slate-800">{{ $revision->reason }}</p><p class="mt-1 text-xs text-slate-500">{{ $revision->correctedBy->name }} · {{ $revision->created_at->format('d M Y, H:i') }}</p></div>@endforeach</div></section>@endif
        </aside>
    </div>
</x-app-layout>
