<x-public-layout :title="'Booking '.$clinic->name">
    <div class="mx-auto max-w-4xl px-5 py-12 sm:px-8">
        <div class="mb-8"><a href="{{ route('public.clinic.show', $clinic) }}" class="text-sm font-bold text-clinic-600">← {{ $clinic->name }}</a><h1 class="mt-4 text-3xl font-extrabold text-clinic-950">Buat booking kunjungan</h1><p class="mt-2 text-slate-500">Pilih layanan dan sesi praktik, lalu isi data pasien.</p></div>
        @if($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700"><p class="font-bold">Periksa kembali data berikut:</p><ul class="mt-2 list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
        <form method="POST" action="{{ route('public.booking.store', $clinic) }}" class="space-y-6" x-data="{ submitting: false }" @submit="submitting = true">@csrf<input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', $idempotencyKey) }}">
            <section class="clinic-card p-6 sm:p-8"><h2 class="text-lg font-extrabold text-clinic-950">1. Jadwal kunjungan</h2><div class="mt-6 grid gap-5 md:grid-cols-2">
                <div><label class="clinic-label" for="doctor_id">Dokter</label><select class="clinic-input" id="doctor_id" name="doctor_id" required><option value="">Pilih dokter</option>@foreach($clinic->doctors as $doctor)<option value="{{ $doctor->id }}" @selected(old('doctor_id') == $doctor->id)>{{ $doctor->user->name }} — {{ $doctor->specialization }}</option>@endforeach</select></div>
                <div><label class="clinic-label" for="service_id">Layanan</label><select class="clinic-input" id="service_id" name="service_id" required><option value="">Pilih layanan</option>@foreach($clinic->services as $service)<option value="{{ $service->id }}" @selected(old('service_id') == $service->id)>{{ $service->name }} — Rp {{ number_format((float) $service->price, 0, ',', '.') }}</option>@endforeach</select></div>
                <div><label class="clinic-label" for="doctor_schedule_id">Sesi praktik</label><select class="clinic-input" id="doctor_schedule_id" name="doctor_schedule_id" required><option value="">Pilih sesi</option>@foreach($clinic->doctors as $doctor)@foreach($doctor->schedules as $schedule)<option value="{{ $schedule->id }}" @selected(old('doctor_schedule_id') == $schedule->id)>{{ $doctor->user->name }} · {{ $schedule->day_name }} · {{ substr($schedule->start_time, 0, 5) }}–{{ substr($schedule->end_time, 0, 5) }}</option>@endforeach @endforeach</select></div>
                <div><label class="clinic-label" for="appointment_date">Tanggal kunjungan</label><input class="clinic-input" id="appointment_date" name="appointment_date" type="date" min="{{ now($clinic->settings?->timezone ?? 'Asia/Jakarta')->toDateString() }}" max="{{ now($clinic->settings?->timezone ?? 'Asia/Jakarta')->addDays(30)->toDateString() }}" value="{{ old('appointment_date') }}" required></div>
            </div></section>
            <section class="clinic-card p-6 sm:p-8"><h2 class="text-lg font-extrabold text-clinic-950">2. Data pasien</h2><p class="mt-2 text-sm text-slate-500">Data ini digunakan klinik untuk menyiapkan kunjungan Anda.</p><div class="mt-6 grid gap-5 md:grid-cols-2">
                <div class="md:col-span-2"><label class="clinic-label" for="name">Nama lengkap</label><input class="clinic-input" id="name" name="name" value="{{ old('name', auth()->user()?->name) }}" required></div>
                <div><label class="clinic-label" for="nik">NIK (opsional)</label><input class="clinic-input" id="nik" name="nik" value="{{ old('nik') }}"></div><div><label class="clinic-label" for="birth_date">Tanggal lahir</label><input class="clinic-input" id="birth_date" name="birth_date" type="date" max="{{ now()->toDateString() }}" value="{{ old('birth_date') }}" required></div>
                <div><label class="clinic-label" for="gender">Jenis kelamin</label><select class="clinic-input" id="gender" name="gender" required><option value="">Pilih</option><option value="MALE" @selected(old('gender') === 'MALE')>Laki-laki</option><option value="FEMALE" @selected(old('gender') === 'FEMALE')>Perempuan</option></select></div><div><label class="clinic-label" for="phone">Nomor telepon</label><input class="clinic-input" id="phone" name="phone" value="{{ old('phone') }}" required></div>
                <div><label class="clinic-label" for="email">Email (opsional)</label><input class="clinic-input" id="email" name="email" type="email" value="{{ old('email', auth()->user()?->email) }}"></div><div><label class="clinic-label" for="address">Alamat (opsional)</label><input class="clinic-input" id="address" name="address" value="{{ old('address') }}"></div>
                <div class="md:col-span-2"><label class="clinic-label" for="notes">Catatan (opsional)</label><textarea class="clinic-input" id="notes" name="notes" rows="3">{{ old('notes') }}</textarea></div>
            </div></section>
            <div class="flex items-center justify-between gap-4"><p class="text-xs leading-5 text-slate-500">Simpan halaman konfirmasi setelah booking berhasil untuk melihat status atau membatalkan.</p><x-clinic-button variant="primary" class="shrink-0 disabled:opacity-60" x-bind:disabled="submitting"><span x-show="!submitting">Konfirmasi booking</span><span x-show="submitting" x-cloak>Memproses…</span></x-clinic-button></div>
        </form>
    </div>
</x-public-layout>
