<x-public-layout title="Status booking — ClinicOS">
    <div class="mx-auto max-w-3xl px-5 py-12 sm:px-8">
        @if(session('status'))<div class="mb-6 rounded-2xl border border-clinic-200 bg-clinic-50 p-4 text-sm font-semibold text-clinic-700">{{ session('status') }}</div>@endif
        <div class="clinic-card overflow-hidden"><div class="bg-clinic-950 p-7 text-white sm:p-9"><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-300">Status booking</p><div class="mt-4 flex flex-wrap items-end justify-between gap-5"><div><h1 class="text-3xl font-extrabold">{{ $appointment->booking_code }}</h1><p class="mt-2 text-sm text-slate-300">{{ $appointment->clinic->name }}</p></div><span class="rounded-full bg-white/10 px-4 py-2 text-sm font-bold">{{ $appointment->status->value }}</span></div></div>
            <div class="grid gap-6 p-7 sm:grid-cols-2 sm:p-9"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Nomor antrean</p><p class="mt-2 font-display text-4xl font-extrabold text-clinic-600">{{ $appointment->queue->display_number }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Pasien</p><p class="mt-2 font-bold text-slate-900">{{ $appointment->patient->name }}</p><p class="mt-1 text-sm text-slate-500">RM {{ $appointment->patient->medical_record_number }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Dokter</p><p class="mt-2 font-bold text-slate-900">{{ $appointment->doctor->user->name }}</p><p class="mt-1 text-sm text-slate-500">{{ $appointment->service_name }}</p></div><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Jadwal</p><p class="mt-2 font-bold text-slate-900">{{ $appointment->appointment_date->translatedFormat('l, d F Y') }}</p><p class="mt-1 text-sm text-slate-500">{{ substr($appointment->schedule->start_time, 0, 5) }}–{{ substr($appointment->schedule->end_time, 0, 5) }}</p></div></div>
            @if($appointment->status === \App\AppointmentStatus::Booked)<div class="border-t border-slate-100 p-7 sm:p-9"><form method="POST" action="{{ route('public.booking.cancel', $appointment) }}" onsubmit="return confirm('Batalkan booking ini?')">@csrf<input type="hidden" name="token" value="{{ $token }}"><label class="clinic-label" for="cancel_reason">Alasan pembatalan (opsional)</label><div class="flex flex-col gap-3 sm:flex-row"><input class="clinic-input" id="cancel_reason" name="cancel_reason" maxlength="500"><x-clinic-button variant="secondary" class="shrink-0 text-red-600">Batalkan booking</x-clinic-button></div></form></div>@endif
        </div><p class="mt-5 text-center text-xs leading-5 text-slate-500">Tautan ini bersifat rahasia. Simpan untuk melihat status booking Anda.</p>
    </div>
</x-public-layout>
