<x-public-layout :title="$clinic->name.' — ClinicOS'">
    <section class="bg-clinic-950 text-white">
        <div class="mx-auto grid max-w-6xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-[1fr_auto] lg:items-end lg:py-20">
            <div><span class="inline-flex rounded-full bg-white/10 px-3 py-1.5 text-xs font-bold uppercase tracking-wider text-clinic-200">Profil klinik</span><h1 class="mt-5 text-4xl font-extrabold sm:text-5xl">{{ $clinic->name }}</h1><p class="mt-5 max-w-2xl leading-7 text-slate-300">{{ $clinic->description ?: 'Pelayanan kesehatan dengan pendaftaran yang mudah dan jadwal yang transparan.' }}</p><div class="mt-6 flex flex-wrap gap-5 text-sm text-slate-300"><span>{{ $clinic->address }}</span><span>{{ $clinic->phone }}</span></div></div>
            <div class="flex flex-col gap-3 sm:flex-row"><a href="{{ route('public.queue.index', $clinic) }}" class="clinic-button-secondary border-white/20 bg-white/10 px-7 py-4 text-white hover:bg-white/20 hover:text-white">Lihat antrean</a><a href="{{ route('public.booking.create', $clinic) }}" class="clinic-button-primary px-7 py-4">Buat booking</a></div>
        </div>
    </section>
    <div class="mx-auto max-w-6xl space-y-14 px-5 py-14 sm:px-8">
        <section><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">Layanan aktif</p><h2 class="mt-2 text-2xl font-extrabold text-clinic-950">Pilih kebutuhan perawatan</h2><div class="mt-7 grid gap-4 md:grid-cols-2 lg:grid-cols-3">@forelse($clinic->services as $service)<article class="clinic-card p-6"><h3 class="font-extrabold text-slate-900">{{ $service->name }}</h3><p class="mt-2 text-sm leading-6 text-slate-500">{{ $service->description }}</p><div class="mt-5 flex items-end justify-between"><p class="font-display text-lg font-extrabold text-clinic-700">Rp {{ number_format((float) $service->price, 0, ',', '.') }}</p><span class="text-xs font-semibold text-slate-400">{{ $service->duration_minutes }} menit</span></div></article>@empty<p class="text-slate-500">Belum ada layanan aktif.</p>@endforelse</div></section>
        <section><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">Dokter & sesi</p><h2 class="mt-2 text-2xl font-extrabold text-clinic-950">Jadwal praktik</h2><div class="mt-7 grid gap-5 lg:grid-cols-2">@forelse($clinic->doctors as $doctor)<article class="clinic-card p-6"><div class="flex items-start gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-clinic-100 font-display text-lg font-extrabold text-clinic-700">{{ str($doctor->user->name)->substr(0, 1)->upper() }}</div><div><h3 class="font-extrabold text-slate-900">{{ $doctor->user->name }}</h3><p class="mt-1 text-sm text-clinic-600">{{ $doctor->specialization }}</p></div></div><div class="mt-5 flex flex-wrap gap-2">@foreach($doctor->schedules as $schedule)<span class="rounded-xl bg-slate-50 px-3 py-2 text-xs font-semibold text-slate-600">{{ $schedule->day_name }}, {{ substr($schedule->start_time, 0, 5) }}–{{ substr($schedule->end_time, 0, 5) }}</span>@endforeach</div></article>@empty<p class="text-slate-500">Belum ada jadwal dokter aktif.</p>@endforelse</div></section>
    </div>
</x-public-layout>
