@php($editing = isset($patient))
<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">Registrasi pasien</p><h1 class="mt-1 text-xl font-extrabold text-clinic-950">{{ $editing ? 'Edit pasien' : 'Pasien baru' }}</h1></div></x-slot>
    <form method="POST" action="{{ $editing ? route('receptionist.patients.update', $patient) : route('receptionist.patients.store') }}" class="mx-auto max-w-4xl space-y-6" x-data="{ submitting:false }" @submit="submitting=true">@csrf @if($editing)@method('PUT')@endif
        <div><h2 class="text-2xl font-extrabold text-clinic-950">{{ $editing ? $patient->name : 'Daftarkan pasien' }}</h2><p class="mt-2 text-sm text-slate-500">Nomor rekam medis dibuat otomatis dan unik untuk klinik.</p></div>
        <section class="clinic-card p-6 sm:p-8"><div class="grid gap-5 md:grid-cols-2">
            <div class="md:col-span-2"><label class="clinic-label" for="name">Nama lengkap</label><input class="clinic-input" id="name" name="name" value="{{ old('name', $patient->name ?? '') }}" required><x-input-error :messages="$errors->get('name')" class="mt-2" /></div>
            <div><label class="clinic-label" for="nik">NIK (opsional)</label><input class="clinic-input" id="nik" name="nik" value="{{ old('nik', $patient->nik ?? '') }}"><x-input-error :messages="$errors->get('nik')" class="mt-2" /></div><div><label class="clinic-label" for="birth_date">Tanggal lahir</label><input class="clinic-input" id="birth_date" name="birth_date" type="date" max="{{ now()->toDateString() }}" value="{{ old('birth_date', isset($patient) ? $patient->birth_date->toDateString() : '') }}" required><x-input-error :messages="$errors->get('birth_date')" class="mt-2" /></div>
            <div><label class="clinic-label" for="gender">Jenis kelamin</label><select class="clinic-input" id="gender" name="gender" required><option value="">Pilih</option><option value="MALE" @selected(old('gender', $patient->gender ?? '') === 'MALE')>Laki-laki</option><option value="FEMALE" @selected(old('gender', $patient->gender ?? '') === 'FEMALE')>Perempuan</option></select></div><div><label class="clinic-label" for="phone">Nomor telepon</label><input class="clinic-input" id="phone" name="phone" value="{{ old('phone', $patient->phone ?? '') }}" required></div>
            <div><label class="clinic-label" for="email">Email</label><input class="clinic-input" id="email" name="email" type="email" value="{{ old('email', $patient->email ?? '') }}"></div><div><label class="clinic-label" for="address">Alamat</label><input class="clinic-input" id="address" name="address" value="{{ old('address', $patient->address ?? '') }}"></div>
            <div class="md:col-span-2"><input type="hidden" name="is_active" value="0"><label class="inline-flex items-center gap-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $patient->is_active ?? true)) class="rounded border-slate-300 text-clinic-500 focus:ring-clinic-500">Pasien aktif</label></div>
        </div></section>
        <div class="flex justify-end gap-3"><a href="{{ route('receptionist.patients.index') }}" class="clinic-button-secondary" wire:navigate>Batal</a><button class="clinic-button-primary disabled:opacity-60" :disabled="submitting">Simpan pasien</button></div>
    </form>
</x-app-layout>
