@php($editing = isset($schedule))
<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">Operasional</p><h1 class="mt-1 text-xl font-extrabold text-clinic-950">{{ $editing ? 'Edit jadwal' : 'Tambah jadwal' }}</h1></div></x-slot>
    <div class="mx-auto max-w-3xl"><div class="mb-7"><h2 class="text-2xl font-extrabold text-clinic-950">Sesi praktik dokter</h2><p class="mt-2 text-sm text-slate-500">Sistem mencegah jadwal bertabrakan dan sesi di luar jam operasional.</p></div>
        <form method="POST" action="{{ $editing ? route('admin.doctor-schedules.update', $schedule) : route('admin.doctor-schedules.store') }}" class="space-y-6" x-data="{ submitting: false }" @submit="submitting = true">@csrf @if ($editing) @method('PUT') @endif
            <section class="clinic-card p-6 sm:p-8"><div class="grid gap-6 md:grid-cols-2">
                <div class="md:col-span-2"><label class="clinic-label" for="doctor_id">Dokter</label><select class="clinic-input" id="doctor_id" name="doctor_id" required><option value="">Pilih dokter</option>@foreach ($doctors as $doctor)<option value="{{ $doctor->id }}" @selected((int) old('doctor_id', $schedule->doctor_id ?? 0) === $doctor->id)>{{ $doctor->user->name }} — {{ $doctor->specialization }}</option>@endforeach</select><x-input-error :messages="$errors->get('doctor_id')" class="mt-2" /></div>
                <div><label class="clinic-label" for="day_of_week">Hari</label><select class="clinic-input" id="day_of_week" name="day_of_week" required>@foreach (\App\Models\DoctorSchedule::DAYS as $value => $label)<option value="{{ $value }}" @selected((int) old('day_of_week', $schedule->day_of_week ?? 1) === $value)>{{ $label }}</option>@endforeach</select><x-input-error :messages="$errors->get('day_of_week')" class="mt-2" /></div>
                <div><label class="clinic-label" for="quota">Kuota pasien</label><input class="clinic-input" id="quota" name="quota" type="number" min="1" max="500" value="{{ old('quota', $schedule->quota ?? 10) }}" required><x-input-error :messages="$errors->get('quota')" class="mt-2" /></div>
                <div><label class="clinic-label" for="start_time">Jam mulai</label><input class="clinic-input" id="start_time" name="start_time" type="time" value="{{ old('start_time', $editing ? substr($schedule->start_time, 0, 5) : '08:00') }}" required><x-input-error :messages="$errors->get('start_time')" class="mt-2" /></div>
                <div><label class="clinic-label" for="end_time">Jam selesai</label><input class="clinic-input" id="end_time" name="end_time" type="time" value="{{ old('end_time', $editing ? substr($schedule->end_time, 0, 5) : '12:00') }}" required><x-input-error :messages="$errors->get('end_time')" class="mt-2" /></div>
                <div class="md:col-span-2"><input type="hidden" name="is_active" value="0"><label class="inline-flex items-center gap-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="is_active" value="1" @checked(old('is_active', $schedule->is_active ?? true)) class="rounded border-slate-300 text-clinic-500 focus:ring-clinic-500">Jadwal aktif</label></div>
            </div></section>
            <div class="flex justify-end gap-3"><a href="{{ route('admin.doctor-schedules.index') }}" class="clinic-button-secondary" wire:navigate>Batal</a><button type="submit" class="clinic-button-primary disabled:cursor-wait disabled:opacity-60" :disabled="submitting"><span x-show="! submitting">{{ $editing ? 'Simpan perubahan' : 'Tambah jadwal' }}</span><span x-show="submitting" x-cloak>Menyimpan…</span></button></div>
        </form>
    </div>
</x-app-layout>
