<x-app-layout>
    <x-slot name="header"><div><p class="text-xs font-bold uppercase tracking-[0.16em] text-clinic-600">Pendaftaran</p><h1 class="mt-1 text-xl font-extrabold text-clinic-950">Booking baru</h1></div></x-slot>
    <div class="mx-auto max-w-4xl"><div class="mb-7"><h2 class="text-2xl font-extrabold text-clinic-950">Daftarkan kunjungan</h2><p class="mt-2 text-sm text-slate-500">Pilih pasien yang sudah terdaftar agar tidak membuat data duplikat.</p></div>@if($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-sm text-red-700">{{ $errors->first() }}</div>@endif
        <form method="POST" action="{{ route('receptionist.appointments.store') }}" class="space-y-6" x-data="{ newPatient: {{ old('patient_id', request('patient_id')) ? 'false' : 'true' }}, submitting:false }" @submit="submitting=true">@csrf<input type="hidden" name="idempotency_key" value="{{ old('idempotency_key', $idempotencyKey) }}">
            <section class="clinic-card p-6 sm:p-8"><div class="flex gap-3"><button type="button" @click="newPatient=false" :class="!newPatient ? 'bg-clinic-500 text-white' : 'bg-slate-100 text-slate-600'" class="rounded-xl px-4 py-2 text-sm font-bold">Pasien terdaftar</button><button type="button" @click="newPatient=true" :class="newPatient ? 'bg-clinic-500 text-white' : 'bg-slate-100 text-slate-600'" class="rounded-xl px-4 py-2 text-sm font-bold">Pasien baru</button></div>
                <div x-show="!newPatient" class="mt-6"><label class="clinic-label" for="patient_id">Pilih pasien</label><select class="clinic-input" id="patient_id" name="patient_id" :disabled="newPatient"><option value="">Pilih pasien</option>@foreach($patients as $patient)<option value="{{ $patient->id }}" @selected(old('patient_id', request('patient_id')) == $patient->id)>{{ $patient->medical_record_number }} — {{ $patient->name }} — {{ $patient->phone }}</option>@endforeach</select></div>
                <div x-show="newPatient" class="mt-6 grid gap-5 md:grid-cols-2"><div class="md:col-span-2"><label class="clinic-label">Nama lengkap</label><input class="clinic-input" name="name" value="{{ old('name') }}" :disabled="!newPatient"></div><div><label class="clinic-label">NIK</label><input class="clinic-input" name="nik" value="{{ old('nik') }}" :disabled="!newPatient"></div><div><label class="clinic-label">Tanggal lahir</label><input class="clinic-input" name="birth_date" type="date" value="{{ old('birth_date') }}" :disabled="!newPatient"></div><div><label class="clinic-label">Jenis kelamin</label><select class="clinic-input" name="gender" :disabled="!newPatient"><option value="MALE">Laki-laki</option><option value="FEMALE">Perempuan</option></select></div><div><label class="clinic-label">Telepon</label><input class="clinic-input" name="phone" value="{{ old('phone') }}" :disabled="!newPatient"></div><div><label class="clinic-label">Email</label><input class="clinic-input" name="email" type="email" value="{{ old('email') }}" :disabled="!newPatient"></div><div><label class="clinic-label">Alamat</label><input class="clinic-input" name="address" value="{{ old('address') }}" :disabled="!newPatient"></div></div>
            </section>
            <section class="clinic-card p-6 sm:p-8"><h3 class="text-lg font-extrabold text-clinic-950">Jadwal & layanan</h3><div class="mt-6 grid gap-5 md:grid-cols-2"><div><label class="clinic-label">Dokter</label><select class="clinic-input" name="doctor_id" required><option value="">Pilih dokter</option>@foreach($doctors as $doctor)<option value="{{ $doctor->id }}">{{ $doctor->user->name }} — {{ $doctor->specialization }}</option>@endforeach</select></div><div><label class="clinic-label">Layanan</label><select class="clinic-input" name="service_id" required><option value="">Pilih layanan</option>@foreach($doctors->flatMap->services->unique('id') as $service)<option value="{{ $service->id }}">{{ $service->name }}</option>@endforeach</select></div><div><label class="clinic-label">Sesi praktik</label><select class="clinic-input" name="doctor_schedule_id" required><option value="">Pilih sesi</option>@foreach($doctors as $doctor)@foreach($doctor->schedules as $schedule)<option value="{{ $schedule->id }}">{{ $doctor->user->name }} · {{ $schedule->day_name }} · {{ substr($schedule->start_time,0,5) }}–{{ substr($schedule->end_time,0,5) }}</option>@endforeach @endforeach</select></div><div><label class="clinic-label">Tanggal</label><input class="clinic-input" name="appointment_date" type="date" min="{{ now()->toDateString() }}" max="{{ now()->addDays(30)->toDateString() }}" required></div><div class="md:col-span-2"><label class="clinic-label">Catatan</label><textarea class="clinic-input" name="notes" rows="3">{{ old('notes') }}</textarea></div></div></section>
            <div class="flex justify-end gap-3"><a href="{{ route('receptionist.appointments.index') }}" class="clinic-button-secondary" wire:navigate>Batal</a><button class="clinic-button-primary disabled:opacity-60" :disabled="submitting">Buat booking</button></div>
        </form>
    </div>
</x-app-layout>
